### ISSUE TITLE
WebGUI Error:  Unhandled rejection TypeError: Cannot read property 'raw_up' of undefined

### ISSUE THREAD

**Issue by WindyCitySDR** [uw-ictd/colte#55]
Hello,

Thank you for creating such an outstanding program, but though I've been able to get the WebAdmin working, (Pretty slick indeed), I've YET to be able to get the "WebGUI" to work and get the following error:

TestBox@TestBox/colte/webgui$ sudo npm start

> webapp@0.0.0 start /home/TestBox/colte/webgui
> babel-node ./bin/www --presets es2015,stage-2

GET / 302 177.681 ms - 58
Web Request From: 127.0.0.1
Unhandled rejection TypeError: Cannot read property 'raw_up' of undefined
    at /home/TestBox/colte/webgui/routes/status.js:12:47
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Builder.Target.then
(/home/TestBox/colte/webgui/node_modules/knex-paginator/node_modules/knex/lib/interface.js:27:24)
    at /home/TestBox/colte/webgui/routes/status.js:11:27
    at Layer.handle [as handle_request]
(/home/TestBox/colte/webgui/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/TestBox/colte/webgui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch
(/home/TestBox/colte/webgui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request]
(/home/TestBox/colte/webgui/node_modules/express/lib/router/layer.js:95:5)
    at /home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params
(/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:335:12)
    at next (/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle
(/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:174:3)
    at router (/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request]
(/home/TestBox/colte/webgui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix
(/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:317:13)
    at /home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params
(/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:335:12)
    at next (/home/TestBox/colte/webgui/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error
(/home/TestBox/colte/webgui/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)

I'm stumped as to which file needs to be modified to correct this "raw_up" error.

Please assist and thank you for this program!

**Comment by josectheone** [comment]
You need to access from the lte network ip subnet.

**Comment by matt9j** [comment]
As indicated by josectheone, this issue arose when you were accessing the user gui interface from a device not on the LTE subnet. I'm hoping to re-work how the network is brought online for the first time and smooth out a lot of these rough edges from the UI.
